export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";
export const FETCH_POST_RESET = "FETCH_POST_RESET";

export const SUBMIT_POST_REQUEST = "SUBMIT_POST_REQUEST";
export const SUBMIT_POST_SUCCESS = "SUBMIT_POST_SUCCESS";
export const SUBMIT_POST_FAILURE = "SUBMIT_POST_FAILURE";
export const SUBMIT_POST_RESET = "SUBMIT_POST_RESET";

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';